### ISSUE TITLE
Examples with popular email programs

### ISSUE THREAD

**Issue by tacman** [secit-pl/imap-bundle#42]
I keep trying with gmail and zohomail but can't connect.  Either I have to enable something on the providers, or I'm not configuring this right.   Any suggestions?  An example with gmail (without the password, of course) would be helpful. And even recommendations of an email provider, I need to receive some emails will need to set up a new account for this anyway.

Thanks.

```yaml
imap:
    connections:
       gmail:
         imap_path: "{imap.gmail.com:993}INBOX"
         username: "tacman@gmail.com"
         password: "<password>"

      zoho:
            imap_path: "{imappro.zoho.com:993}INBOX"
            username: "museado@zohomail.com"
            password: "<password>"
            attachments_dir: "%kernel.project_dir%/var/imap/attachments"
            create_attachments_dir_if_not_exists: true # default true
            created_attachments_dir_permissions: 777 # default 770
            server_encoding: "UTF-8"
```

+------------+-----------------------------------------------------------+-----------------------------+----------------------+---------+
| Connection | Connect Result                                            | Mailbox                     | Username             | Enabled |
+------------+-----------------------------------------------------------+-----------------------------+----------------------+---------+
| zoho       | FAILED: [CLOSED] IMAP connection broken (server response) | {imappro.zoho.com:993}INBOX | museado@zohomail.com | YES     |
+------------+-----------------------------------------------------------+-----------------------------+----------------------+---------+
Total connections: 1

**Comment by tacman** [comment]
I was able to get it to work with gmail by changing the config and signing up for an app password:

```yaml
      gmail:
        imap_path: "{imap.gmail.com:993/imap/ssl}INBOX"
        username: "tacman@gmail.com"
        password: "<app-password>"
```
