### ISSUE TITLE
The child config "connections" under "imap" must be configured.

### ISSUE THREAD

**Issue by gamersalpha** [secit-pl/imap-bundle#47]
**Description of the issue**

I'm trying to create a Symfony 7.1 project and want to use the ImapBundle for IMAP email management. I followed the
installation instructions and installed the bundle with the command `composer require secit-pl/imap-bundle`.

However, when running the `php bin/console debug:config imap` command, I get the following error:

```
In ArrayNode.php line 213:
The child config "connections" under "imap" must be configured.
```

I can see the `imap` section in my `bundles.php` file, but I don't understand why the system requires additional configurations
under this section.

**Additional details**

* Symfony version: 7.1
* ImapBundle version: ?
* Current configuration:
```yaml
SecIT\ImapBundle\ImapBundle::class => ['all' => true],
```

```yaml
imap:
    connections:
        example:
            imap_path: "{localhost:993/imap/ssl/novalidate-cert}INBOX"
            username: "email@example.com"
            password: "password"

        another:
            imap_path: "{localhost:143}INBOX"
            username: "username"
            password: "password"
            attachments_dir: "%kernel.project_dir%/var/imap/attachments"
            server_encoding: "UTF-8"

        full_config:
            imap_path: "{localhost:143}INBOX"
            username: "username"
            password: "password"
            attachments_dir: "%kernel.project_dir%/var/imap/attachments"
            create_attachments_dir_if_not_exists: true # default true
            created_attachments_dir_permissions: 777 # default 770
            server_encoding: "UTF-8"
            enabled: true
```

**Help needed**

I'm sorry for the inconvenience and would greatly appreciate your help in resolving this issue. Thank you in advance!
